title: Gbenga Adesoji
logo: pix.jpg
description: I am a dedicated Data Professional with over three years of experience; I specialize in interrogating and transforming complex datasets into actionable business insights that help achieve organizational goals. Proficient in MS Excel, Power BI, SQL, and Tableau—with hands-on familiarity in Microsoft Fabric—I bring a strong analytical mindset and technical precision to every project. I am passionate about "listening to what the data is saying," uncovering hidden trends, and translating raw numbers into compelling visual stories that help facilitate a data-driven decision-making process.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
